[[games]]
key = "speed-math"
name = "Lightning Multiplication"
type = "timed_math"
description = "Solve two-digit multiplication problems quickly to earn a bigger reward."
enabled = true
base_reward = 12.0
max_time = 12.0
min_reward = 1.0
min_factor = 0.05

[[games]]
key = "reaction-test"
name = "Reaction Time Reflex"
type = "reaction"
description = "Wait for the signal, then click instantly. Faster reactions lead to higher payouts."
enabled = true
base_reward = 9.0
max_time = 0.8
cooldown = 1.0

[[games]]
key = "daily-trivia"
name = "Seeded Trivia Challenge"
type = "trivia"
description = "Everyone sees the same questions, but the order is shuffled per player."
enabled = true
question_set = "general"
reward = 6.0
rating_reward = 1.5

[[games]]
key = "animal-spotter"
name = "Animal Spotter"
type = "trivia"
description = "Identify the animal shown in each illustration."
enabled = true
question_set = "animals"
reward = 6.0
rating_reward = 1.5

[[games]]
key = "omega-choice"
name = "Omega's Boxes"
type = "newcomb"
description = "A suspicious take on Newcomb's problem. Two-boxing never works."
enabled = true
payout_small = 25.0
payout_large = 180.0
payout_both = 25.0

[[games]]
key = "task-swipe-card"
name = "Swipe the Admin Card"
type = "among_us"
description = "Drag your card across the reader at just the right speed."
enabled = true
task = "swipe_card"
base_reward = 7.0
ideal_time = 1.2
tolerance = 0.6

[[games]]
key = "task-prime-shields"
name = "Prime the Shields"
type = "among_us"
description = "Toggle every shield segment until they're all glowing."
enabled = true
task = "prime_shields"
base_reward = 6.0

[[games]]
key = "task-align-engine"
name = "Align the Engine Output"
type = "among_us"
description = "Line up the thruster indicator with the target marker."
enabled = true
task = "align_engine"
base_reward = 8.0
precision = 3.0

[[games]]
key = "telestrations"
name = "Telestrations Relay"
type = "telestrations"
description = "Start a drawing chain or add the next clue with alternating sketches and captions."
enabled = true
max_turns = 2
upvote_reward = 2.0
seed_prompts = ["dragon", "spaceship", "mysterious treasure"]
